import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/layout/Navigation";
import LenisProvider from "@/components/providers/LenisProv";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Navigation />
        </div>
        <LenisProvider>
          <div className=" mt-20">{children}</div>
        </LenisProvider>
        <div className="h-screen"></div>
      </body>
    </html>
  );
}
